language: cpp

matrix:
  include:
    - compiler: gcc
      env: CMAKE_CXX_COMPILER=g++-5 CMAKE_C_COMPILER=gcc-5
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
    - compiler: clang
      env: CMAKE_CXX_COMPILER=/usr/bin/clang++ CMAKE_C_COMPILER=/usr/bin/clang
      os: osx
    - compiler: gcc
      env: CMAKE_CXX_COMPILER=/usr/bin/g++ CMAKE_C_COMPILER=/usr/bin/gcc
      os: osx

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$CMAKE_CXX_COMPILER -DCMAKE_C_COMPILER=$CMAKE_C_COMPILER ../
  - make
